name: flutter_eversign
description: A flutter package to show and interact with eversign iframes
version: 0.0.1+1
homepage: https://github.com/zwapin/flutter_eversign

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
